# Generated by Django 5.1.6 on 2025-03-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0005_remove_prediction_user_remove_user_age_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
