# Generated by Django 5.1.6 on 2025-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0007_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
