# Generated by Django 5.1.6 on 2025-03-29 07:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0009_prediction_risk_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                help_text="User who authored this blog post",
                on_delete=django.db.models.deletion.CASCADE,
                to="predictor.user",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(help_text="Main content of the blog post"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, help_text="Timestamp of blog creation"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the blog post",
                null=True,
                upload_to="blog_images/",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(help_text="Title of the blog post", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="User's age in years", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, help_text="Timestamp of user creation"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="User's email address", max_length=120, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Hashed password for the user",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="retype_password",
            field=models.CharField(
                blank=True,
                help_text="Temporary field for password confirmation (not stored)",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                help_text="Unique username for the user",
                max_length=120,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="Prediction",
        ),
    ]
