# Generated by Django 5.1.6 on 2025-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0014_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                help_text="User's gender",
                max_length=10,
                null=True,
            ),
        ),
    ]
