# Generated by Django 5.1.6 on 2025-03-09 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "user_name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_name",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("email", models.CharField(max_length=120, unique=True)),
                ("password", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "retype_password",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
